language: python
python:
    "2.7"
install:
    - pip install Whoosh==2.5.6
    - pip install SQLAlchemy==0.9.7
    - "pip install -e 'git+https://github.com/veekun/pokedex#egg=Pokedex'"
    - "pip install -e 'git+https://github.com/hamperbot/hamper#egg=hamper'"
    - pip install .
before_script:
    - pokedex setup -v
script:
    - pyflakes .
    - python -munittest hamper_pokedex
